---
- name: Setup systemd Service for mountpoints
  template:
    src: systemd_mount.j2
    dest: "/etc/systemd/system/{{ item.value.mount[1:] | replace('/', '-') }}.mount"
    owner: root
    group: root
    mode:
  with_dict: "{{ mounts }}"
  notify: Enable systemd mount

- meta: flush_handlers
